### PR TITLE
support angular routesegment

### PR DESCRIPTION
**Pull request by MillerRen**
support angular routesegment

### CODE REVIEW

**Comment by kingcody** [comment]
Does this require [artch/angular-route-segment](https://github.com/artch/angular-route-segment)?

**Comment by MillerRen** [comment]
@kingcody yes. I forked a new generator `generator-my-angel` that used `angular-route-segment`. But it depend on generator-ng-component.

**Comment by kingcody** [comment]
Instead, you could add `'routeTemplates': '.my-angel-templates/route'` to generator-ng-component's compose options [here](https://github.com/MillerRen/generator-my-angel/blob/master/app/index.js#L224-L232). Then all you would need to do is include the `.my-angel-templates/route` directory [here](https://github.com/MillerRen/generator-my-angel/tree/master/app/templates) (with your generator's route template files).

**Comment by MillerRen** [comment]
@kingcody Thx!

**Comment by kingcody** [comment]
No problem, I'm going to go ahead and close this. Feel free to open an issue if you have any problems with your template integration.

**Pull request closed without merging**
